### ISSUE TITLE
hand-out

### ISSUE THREAD

**Issue by JacksonWang6** [LipeiranNJU/os-workbench#2]
尊敬的前辈您好,我是华科的学弟,对贵校的OS课程非常感兴趣,,非常感谢您上传您写的优秀的代码,想请问一下能否上传一下实验指导书!十分感谢!

**Comment by LipeiranNJU** [comment]
同学你好，我们的课程的视频https://www.bilibili.com/video/BV1N741177F5可以适当参考，书籍为operating system: three easy pieces，由于课程主页需要校园网，我发一下几次实验的网页pdf吧，OJ提交需要校园网环境，所以自己做实验可能验证较为麻烦。祝同学能够有所收获




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"WangAShao"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月8日(星期一) 下午5:45
收件人:&nbsp;"LipeiranNJU/os-workbench"<os-workbench@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[LipeiranNJU/os-workbench] hand-out (#2)





 
尊敬的前辈您好,我是华科的学弟,对贵校的OS课程非常感兴趣,,非常感谢您上传您写的优秀的代码,想请问一下能否上传一下实验指导书!十分感谢!
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的超大附件

Downloads.7z (7.38M, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=20373830a883ba9e3c479a2e1366014e51040952075755554c0e0d01024b0703000215090355014c53055a050605000002005e01356a33250e40565c5a0757124f00423045&t=exs_ftn_download&code=a7805f3a
